{
    "runtime": {
        "name": "wasmer",
        "version": "2.3.0"
    },
    "results": [
        {
            "path": "libstd/env_vars-some.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/io_stdin-beowulf.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/env_args-many.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/io_stderr-beowulf.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/io_stdout-beowulf.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/fs_metadata-file.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/fs_rename-file.wasm",
            "status": "FAIL",
            "message": "thread 'main' panicked at 'assertion failed: fs::rename(old_path, new_path).is_ok()', fs_rename-file.rs:7:3\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\nerror: failed to run `fs_rename-file.wasm`\n│   1: RuntimeError: unreachable\n           at __rust_start_panic (fs_rename-file.wasm[167]:0x5fe7)\n           at rust_panic (fs_rename-file.wasm[160]:0x5c10)\n           at std::panicking::rust_panic_with_hook::h0934220b8bcb5bb0 (fs_rename-file.wasm[159]:0x5b8d)\n           at std::panicking::begin_panic_handler::{{closure}}::hd757106e895f8529 (fs_rename-file.wasm[147]:0x4de0)\n           at std::sys_common::backtrace::__rust_end_short_backtrace::hda2217248ddf29b4 (fs_rename-file.wasm[146]:0x4d4f)\n           at rust_begin_unwind (fs_rename-file.wasm[154]:0x54b8)\n           at core::panicking::panic_fmt::h99615bf411b9c1d7 (fs_rename-file.wasm[244]:0xb9b7)\n           at core::panicking::panic::h6405394cda32a2f1 (fs_rename-file.wasm[249]:0xbe85)\n           at fs_rename_file::main::hafbfd2a7fa2611b2 (fs_rename-file.wasm[24]:0x98a)\n           at core::ops::function::FnOnce::call_once::heaf1808860907d28 (fs_rename-file.wasm[46]:0xe07)\n           at std::sys_common::backtrace::__rust_begin_short_backtrace::hda09ea45a605841c (fs_rename-file.wasm[27]:0x9c8)\n           at std::rt::lang_start::{{closure}}::hc5fed2e04ad85781 (fs_rename-file.wasm[43]:0xd22)\n           at std::rt::lang_start_internal::h357a5b85e7ff400e (fs_rename-file.wasm[114]:0x2dce)\n           at std::rt::lang_start::h43c4f6e564d3bde4 (fs_rename-file.wasm[42]:0xce8)\n           at __original_main (fs_rename-file.wasm[25]:0x9a8)\n           at _start (fs_rename-file.wasm[8]:0x3da)\n           at _start.command_export (fs_rename-file.wasm[316]:0xf61c)\n╰─▶ 2: unreachable\n"
        },
        {
            "path": "libstd/fs_create_dir-existing-directory.wasm",
            "status": "FAIL",
            "message": "thread 'main' panicked at 'assertion failed: fs::create_dir(\\\"fs_create_dir-existing-directory.dir/existing_directory\\\").is_err()', fs_create_dir-existing-directory.rs:4:3\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\nerror: failed to run `fs_create_dir-existing-directory.wasm`\n│   1: RuntimeError: unreachable\n           at __rust_start_panic (fs_create_dir-existing-directory.wasm[183]:0x78a5)\n           at rust_panic (fs_create_dir-existing-directory.wasm[177]:0x76d4)\n           at std::panicking::rust_panic_with_hook::h0934220b8bcb5bb0 (fs_create_dir-existing-directory.wasm[176]:0x7651)\n           at std::panicking::begin_panic_handler::{{closure}}::hd757106e895f8529 (fs_create_dir-existing-directory.wasm[163]:0x689f)\n           at std::sys_common::backtrace::__rust_end_short_backtrace::hda2217248ddf29b4 (fs_create_dir-existing-directory.wasm[162]:0x680e)\n           at rust_begin_unwind (fs_create_dir-existing-directory.wasm[171]:0x6f7c)\n           at core::panicking::panic_fmt::h99615bf411b9c1d7 (fs_create_dir-existing-directory.wasm[261]:0xd343)\n           at core::panicking::panic::h6405394cda32a2f1 (fs_create_dir-existing-directory.wasm[266]:0xd811)\n           at fs_create_dir_existing_directory::main::h8a5d219065744df1 (fs_create_dir-existing-directory.wasm[35]:0xbdc)\n           at core::ops::function::FnOnce::call_once::h99b1625306e09ff2 (fs_create_dir-existing-directory.wasm[54]:0x10da)\n           at std::sys_common::backtrace::__rust_begin_short_backtrace::h8405c7fd7fb44b0f (fs_create_dir-existing-directory.wasm[29]:0xa3e)\n           at std::rt::lang_start::{{closure}}::hf91f361dc0a7e7a2 (fs_create_dir-existing-directory.wasm[45]:0xd85)\n           at std::rt::lang_start_internal::h357a5b85e7ff400e (fs_create_dir-existing-directory.wasm[120]:0x2f82)\n           at std::rt::lang_start::hbe081e06499119fb (fs_create_dir-existing-directory.wasm[44]:0xd4b)\n           at __original_main (fs_create_dir-existing-directory.wasm[36]:0xbfa)\n           at _start (fs_create_dir-existing-directory.wasm[9]:0x424)\n           at _start.command_export (fs_create_dir-existing-directory.wasm[333]:0x10fa8)\n╰─▶ 2: unreachable\n"
        },
        {
            "path": "libstd/io_stderr-hello.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/process_exit-0.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/fs_file_create.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/fs_rename-directory.wasm",
            "status": "FAIL",
            "message": "thread 'main' panicked at 'assertion failed: fs::rename(old_path, new_path).is_ok()', fs_rename-directory.rs:7:3\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\nerror: failed to run `fs_rename-directory.wasm`\n│   1: RuntimeError: unreachable\n           at __rust_start_panic (fs_rename-directory.wasm[167]:0x5fe7)\n           at rust_panic (fs_rename-directory.wasm[160]:0x5c10)\n           at std::panicking::rust_panic_with_hook::h0934220b8bcb5bb0 (fs_rename-directory.wasm[159]:0x5b8d)\n           at std::panicking::begin_panic_handler::{{closure}}::hd757106e895f8529 (fs_rename-directory.wasm[147]:0x4de0)\n           at std::sys_common::backtrace::__rust_end_short_backtrace::hda2217248ddf29b4 (fs_rename-directory.wasm[146]:0x4d4f)\n           at rust_begin_unwind (fs_rename-directory.wasm[154]:0x54b8)\n           at core::panicking::panic_fmt::h99615bf411b9c1d7 (fs_rename-directory.wasm[244]:0xb9b7)\n           at core::panicking::panic::h6405394cda32a2f1 (fs_rename-directory.wasm[249]:0xbe85)\n           at fs_rename_directory::main::hc2b82f4701e6cd58 (fs_rename-directory.wasm[25]:0x99c)\n           at core::ops::function::FnOnce::call_once::h833f6d4079e02f34 (fs_rename-directory.wasm[46]:0xe07)\n           at std::sys_common::backtrace::__rust_begin_short_backtrace::h7bcae36bd2a3bd44 (fs_rename-directory.wasm[24]:0x8b0)\n           at std::rt::lang_start::{{closure}}::h8f0916fc8e27c8b5 (fs_rename-directory.wasm[43]:0xd22)\n           at std::rt::lang_start_internal::h357a5b85e7ff400e (fs_rename-directory.wasm[114]:0x2dce)\n           at std::rt::lang_start::hf97e6e8ad8259a00 (fs_rename-directory.wasm[42]:0xce8)\n           at __original_main (fs_rename-directory.wasm[26]:0x9ba)\n           at _start (fs_rename-directory.wasm[8]:0x3da)\n           at _start.command_export (fs_rename-directory.wasm[316]:0xf61c)\n╰─▶ 2: unreachable\n"
        },
        {
            "path": "libstd/fs_metadata-directory.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/env_args-none.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/env_vars-none.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/main.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/io_stdout-hello.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/process_exit-1.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/io_stdin-hello.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/process_exit-120.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/fs_create_dir-new-directory.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/env_args-some.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libstd/env_vars-many.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "core/clock_get_res-monotonic.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "core/fd_stat_get-stdin.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "core/fd_stat_get-stderr.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "core/sched_yield.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "core/start.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "core/fd_stat_get-stdout.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "core/proc_exit-failure.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "core/clock_get_res-realtime.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "core/proc_exit-success.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/stdout-hello.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/assert-false.wasm",
            "status": "FAIL",
            "message": "--- assert-false.status\t2022-07-29 00:21:32.517342845 +0000\n+++ /tmp/tmp.8se5PYsbHQ/status\t2022-07-29 00:21:43.529921260 +0000\n@@ -1 +1 @@\n-134\n+1\n"
        },
        {
            "path": "libc/stderr-hello.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/fopen-parent-directory.wasm",
            "status": "FAIL",
            "message": "Assertion failed: file == NULL (fopen-parent-directory.c: main: 7)\nerror: failed to run `fopen-parent-directory.wasm`\n│   1: RuntimeError: unreachable\n           at abort (fopen-parent-directory.wasm[16]:0x3d6)\n           at __assert_fail (fopen-parent-directory.wasm[17]:0x428)\n           at __original_main (fopen-parent-directory.wasm[12]:0x333)\n           at _start (fopen-parent-directory.wasm[11]:0x27a)\n╰─▶ 2: unreachable\n"
        },
        {
            "path": "libc/abort.wasm",
            "status": "FAIL",
            "message": "--- abort.status\t2022-07-29 00:21:32.517342845 +0000\n+++ /tmp/tmp.PDVbL8FORS/status\t2022-07-29 00:21:43.645927294 +0000\n@@ -1 +1 @@\n-134\n+1\n"
        },
        {
            "path": "libc/stdin-hello.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/getenv-absent.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/fopen-working-directory.wasm",
            "status": "FAIL",
            "message": "Assertion failed: errno == ENOTCAPABLE (fopen-working-directory.c: main: 8)\nerror: failed to run `fopen-working-directory.wasm`\n│   1: RuntimeError: unreachable\n           at abort (fopen-working-directory.wasm[16]:0x3d6)\n           at __assert_fail (fopen-working-directory.wasm[17]:0x428)\n           at __original_main (fopen-working-directory.wasm[12]:0x393)\n           at _start (fopen-working-directory.wasm[11]:0x27a)\n╰─▶ 2: unreachable\n"
        },
        {
            "path": "libc/clock_gettime-realtime.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/main.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/clock_getres-monotonic.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/clock_gettime-monotonic.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/assert-true.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/exit-failure.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/getenv-present.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/ftruncate.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/exit-success.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/clock_getres-realtime.wasm",
            "status": "PASS",
            "message": ""
        },
        {
            "path": "libc/fopen-directory-parent-directory.wasm",
            "status": "FAIL",
            "message": "Assertion failed: errno == ENOTCAPABLE (fopen-directory-parent-directory.c: main: 8)\nerror: failed to run `fopen-directory-parent-directory.wasm`\n│   1: RuntimeError: unreachable\n           at abort (fopen-directory-parent-directory.wasm[16]:0x3d6)\n           at __assert_fail (fopen-directory-parent-directory.wasm[17]:0x428)\n           at __original_main (fopen-directory-parent-directory.wasm[12]:0x393)\n           at _start (fopen-directory-parent-directory.wasm[11]:0x27a)\n╰─▶ 2: unreachable\n"
        },
        {
            "path": "libc/getentropy.wasm",
            "status": "PASS",
            "message": ""
        }
    ]
}